package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityUuidIdDTOAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdDTOAllPropertiesEquals(EntityUuidIdDTO expected, EntityUuidIdDTO actual) {
        assertEntityUuidIdDTOAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityUuidIdDTOAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdDTOAllUpdatablePropertiesEquals(EntityUuidIdDTO expected, EntityUuidIdDTO actual) {
        assertEntityUuidIdDTOUpdatableFieldsEquals(expected, actual);
        assertEntityUuidIdDTOUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdDTOAutoGeneratedPropertiesEquals(EntityUuidIdDTO expected, EntityUuidIdDTO actual) {
        assertThat(actual)
            .as("Verify EntityUuidIdDTO auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdDTOUpdatableFieldsEquals(EntityUuidIdDTO expected, EntityUuidIdDTO actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdDTOUpdatableRelationshipsEquals(EntityUuidIdDTO expected, EntityUuidIdDTO actual) {
        assertThat(actual)
            .as("Verify EntityUuidIdDTO relationships")
            .satisfies(a -> assertThat(a.getManyToManyBacks()).as("check manyToManyBacks").isEqualTo(expected.getManyToManyBacks()));
    }
}
