package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityCustomIdDTOAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdDTOAllPropertiesEquals(EntityCustomIdDTO expected, EntityCustomIdDTO actual) {
        assertEntityCustomIdDTOAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityCustomIdDTOAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdDTOAllUpdatablePropertiesEquals(EntityCustomIdDTO expected, EntityCustomIdDTO actual) {
        assertEntityCustomIdDTOUpdatableFieldsEquals(expected, actual);
        assertEntityCustomIdDTOUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdDTOAutoGeneratedPropertiesEquals(EntityCustomIdDTO expected, EntityCustomIdDTO actual) {
        assertThat(actual)
            .as("Verify EntityCustomIdDTO auto generated properties")
            .satisfies(a -> assertThat(a.getCustomId()).as("check customId").isEqualTo(expected.getCustomId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdDTOUpdatableFieldsEquals(EntityCustomIdDTO expected, EntityCustomIdDTO actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdDTOUpdatableRelationshipsEquals(EntityCustomIdDTO expected, EntityCustomIdDTO actual) {
        assertThat(actual)
            .as("Verify EntityCustomIdDTO relationships")
            .satisfies(a -> assertThat(a.getManyToManyBacks()).as("check manyToManyBacks").isEqualTo(expected.getManyToManyBacks()));
    }
}
