package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityCustomIdDTORelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdDTORelAllPropertiesEquals(EntityCustomIdDTORel expected, EntityCustomIdDTORel actual) {
        assertEntityCustomIdDTORelAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityCustomIdDTORelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdDTORelAllUpdatablePropertiesEquals(EntityCustomIdDTORel expected, EntityCustomIdDTORel actual) {
        assertEntityCustomIdDTORelUpdatableFieldsEquals(expected, actual);
        assertEntityCustomIdDTORelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdDTORelAutoGeneratedPropertiesEquals(EntityCustomIdDTORel expected, EntityCustomIdDTORel actual) {
        assertThat(actual)
            .as("Verify EntityCustomIdDTORel auto generated properties")
            .satisfies(a -> assertThat(a.getRelatedId()).as("check relatedId").isEqualTo(expected.getRelatedId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdDTORelUpdatableFieldsEquals(EntityCustomIdDTORel expected, EntityCustomIdDTORel actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdDTORelUpdatableRelationshipsEquals(EntityCustomIdDTORel expected, EntityCustomIdDTORel actual) {
        assertThat(actual)
            .as("Verify EntityCustomIdDTORel relationships")
            .satisfies(a -> assertThat(a.getOneToOne()).as("check oneToOne").isEqualTo(expected.getOneToOne()))
            .satisfies(a -> assertThat(a.getOneToOneMapsId()).as("check oneToOneMapsId").isEqualTo(expected.getOneToOneMapsId()))
            .satisfies(a -> assertThat(a.getManyToOne()).as("check manyToOne").isEqualTo(expected.getManyToOne()))
            .satisfies(a -> assertThat(a.getManyToOneMapsId()).as("check manyToOneMapsId").isEqualTo(expected.getManyToOneMapsId()))
            .satisfies(a -> assertThat(a.getManyToManies()).as("check manyToManies").isEqualTo(expected.getManyToManies()))
            .satisfies(a -> assertThat(a.getManyToManyMapsIds()).as("check manyToManyMapsIds").isEqualTo(expected.getManyToManyMapsIds()));
    }
}
