package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityCustomIdRequiredDTOAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdRequiredDTOAllPropertiesEquals(
        EntityCustomIdRequiredDTO expected,
        EntityCustomIdRequiredDTO actual
    ) {
        assertEntityCustomIdRequiredDTOAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityCustomIdRequiredDTOAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdRequiredDTOAllUpdatablePropertiesEquals(
        EntityCustomIdRequiredDTO expected,
        EntityCustomIdRequiredDTO actual
    ) {
        assertEntityCustomIdRequiredDTOUpdatableFieldsEquals(expected, actual);
        assertEntityCustomIdRequiredDTOUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdRequiredDTOAutoGeneratedPropertiesEquals(
        EntityCustomIdRequiredDTO expected,
        EntityCustomIdRequiredDTO actual
    ) {
        assertThat(actual)
            .as("Verify EntityCustomIdRequiredDTO auto generated properties")
            .satisfies(a -> assertThat(a.getCustomId()).as("check customId").isEqualTo(expected.getCustomId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdRequiredDTOUpdatableFieldsEquals(
        EntityCustomIdRequiredDTO expected,
        EntityCustomIdRequiredDTO actual
    ) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdRequiredDTOUpdatableRelationshipsEquals(
        EntityCustomIdRequiredDTO expected,
        EntityCustomIdRequiredDTO actual
    ) {
        assertThat(actual)
            .as("Verify EntityCustomIdRequiredDTO relationships")
            .satisfies(a -> assertThat(a.getManyToManyBacks()).as("check manyToManyBacks").isEqualTo(expected.getManyToManyBacks()));
    }
}
