package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityCustomIdAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdAllPropertiesEquals(EntityCustomId expected, EntityCustomId actual) {
        assertEntityCustomIdAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityCustomIdAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdAllUpdatablePropertiesEquals(EntityCustomId expected, EntityCustomId actual) {
        assertEntityCustomIdUpdatableFieldsEquals(expected, actual);
        assertEntityCustomIdUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdAutoGeneratedPropertiesEquals(EntityCustomId expected, EntityCustomId actual) {
        assertThat(actual)
            .as("Verify EntityCustomId auto generated properties")
            .satisfies(a -> assertThat(a.getCustomId()).as("check customId").isEqualTo(expected.getCustomId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdUpdatableFieldsEquals(EntityCustomId expected, EntityCustomId actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdUpdatableRelationshipsEquals(EntityCustomId expected, EntityCustomId actual) {
        assertThat(actual)
            .as("Verify EntityCustomId relationships")
            .satisfies(a -> assertThat(a.getManyToManyBacks()).as("check manyToManyBacks").isEqualTo(expected.getManyToManyBacks()));
    }
}
