package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityUuidIdRelationshipAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdRelationshipAllPropertiesEquals(
        EntityUuidIdRelationship expected,
        EntityUuidIdRelationship actual
    ) {
        assertEntityUuidIdRelationshipAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityUuidIdRelationshipAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdRelationshipAllUpdatablePropertiesEquals(
        EntityUuidIdRelationship expected,
        EntityUuidIdRelationship actual
    ) {
        assertEntityUuidIdRelationshipUpdatableFieldsEquals(expected, actual);
        assertEntityUuidIdRelationshipUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdRelationshipAutoGeneratedPropertiesEquals(
        EntityUuidIdRelationship expected,
        EntityUuidIdRelationship actual
    ) {
        assertThat(actual)
            .as("Verify EntityUuidIdRelationship auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdRelationshipUpdatableFieldsEquals(
        EntityUuidIdRelationship expected,
        EntityUuidIdRelationship actual
    ) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdRelationshipUpdatableRelationshipsEquals(
        EntityUuidIdRelationship expected,
        EntityUuidIdRelationship actual
    ) {
        assertThat(actual)
            .as("Verify EntityUuidIdRelationship relationships")
            .satisfies(a -> assertThat(a.getOneToOne()).as("check oneToOne").isEqualTo(expected.getOneToOne()))
            .satisfies(a -> assertThat(a.getOneToOneMapsId()).as("check oneToOneMapsId").isEqualTo(expected.getOneToOneMapsId()))
            .satisfies(a -> assertThat(a.getManyToOne()).as("check manyToOne").isEqualTo(expected.getManyToOne()))
            .satisfies(a -> assertThat(a.getManyToOneMapsId()).as("check manyToOneMapsId").isEqualTo(expected.getManyToOneMapsId()))
            .satisfies(a -> assertThat(a.getManyToManies()).as("check manyToManies").isEqualTo(expected.getManyToManies()))
            .satisfies(a -> assertThat(a.getManyToManyMapsIds()).as("check manyToManyMapsIds").isEqualTo(expected.getManyToManyMapsIds()));
    }
}
