package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityCustomIdMapsIdAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdMapsIdAllPropertiesEquals(EntityCustomIdMapsId expected, EntityCustomIdMapsId actual) {
        assertEntityCustomIdMapsIdAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityCustomIdMapsIdAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdMapsIdAllUpdatablePropertiesEquals(EntityCustomIdMapsId expected, EntityCustomIdMapsId actual) {
        assertEntityCustomIdMapsIdUpdatableFieldsEquals(expected, actual);
        assertEntityCustomIdMapsIdUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the derived primary key is set correctly.
     *
     * @param entityToPersist the entity used to persist
     * @param persisted the persisted entity
     */
    public static void assertEntityCustomIdMapsIdMapsIdRelationshipPersistedValue(
        EntityCustomIdMapsId entityToPersist,
        EntityCustomIdMapsId persisted
    ) {
        // Validate the id for MapsId, the ids must be same
        assertThat(entityToPersist.getEntityCustomId().getCustomId()).isEqualTo(persisted.getCustomId());
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdMapsIdAutoGeneratedPropertiesEquals(EntityCustomIdMapsId expected, EntityCustomIdMapsId actual) {
        assertThat(actual)
            .as("Verify EntityCustomIdMapsId auto generated properties")
            .satisfies(a -> assertThat(a.getCustomId()).as("check customId").isEqualTo(expected.getCustomId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdMapsIdUpdatableFieldsEquals(EntityCustomIdMapsId expected, EntityCustomIdMapsId actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityCustomIdMapsIdUpdatableRelationshipsEquals(EntityCustomIdMapsId expected, EntityCustomIdMapsId actual) {
        assertThat(actual)
            .as("Verify EntityCustomIdMapsId relationships")
            .satisfies(a ->
                assertThat(a.getManyToManyMapsIdBacks()).as("check manyToManyMapsIdBacks").isEqualTo(expected.getManyToManyMapsIdBacks())
            );
    }
}
