package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityUuidIdAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdAllPropertiesEquals(EntityUuidId expected, EntityUuidId actual) {
        assertEntityUuidIdAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityUuidIdAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdAllUpdatablePropertiesEquals(EntityUuidId expected, EntityUuidId actual) {
        assertEntityUuidIdUpdatableFieldsEquals(expected, actual);
        assertEntityUuidIdUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdAutoGeneratedPropertiesEquals(EntityUuidId expected, EntityUuidId actual) {
        assertThat(actual)
            .as("Verify EntityUuidId auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdUpdatableFieldsEquals(EntityUuidId expected, EntityUuidId actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityUuidIdUpdatableRelationshipsEquals(EntityUuidId expected, EntityUuidId actual) {
        assertThat(actual)
            .as("Verify EntityUuidId relationships")
            .satisfies(a -> assertThat(a.getManyToManyBacks()).as("check manyToManyBacks").isEqualTo(expected.getManyToManyBacks()));
    }
}
