package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UuidIdFilteringAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUuidIdFilteringAllPropertiesEquals(UuidIdFiltering expected, UuidIdFiltering actual) {
        assertUuidIdFilteringAutoGeneratedPropertiesEquals(expected, actual);
        assertUuidIdFilteringAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUuidIdFilteringAllUpdatablePropertiesEquals(UuidIdFiltering expected, UuidIdFiltering actual) {
        assertUuidIdFilteringUpdatableFieldsEquals(expected, actual);
        assertUuidIdFilteringUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUuidIdFilteringAutoGeneratedPropertiesEquals(UuidIdFiltering expected, UuidIdFiltering actual) {
        assertThat(actual)
            .as("Verify UuidIdFiltering auto generated properties")
            .satisfies(a -> assertThat(a.getCustomId()).as("check customId").isEqualTo(expected.getCustomId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUuidIdFilteringUpdatableFieldsEquals(UuidIdFiltering expected, UuidIdFiltering actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUuidIdFilteringUpdatableRelationshipsEquals(UuidIdFiltering expected, UuidIdFiltering actual) {
        assertThat(actual)
            .as("Verify UuidIdFiltering relationships")
            .satisfies(a -> assertThat(a.getManyToManyBacks()).as("check manyToManyBacks").isEqualTo(expected.getManyToManyBacks()));
    }
}
