package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UuidIdFilteringMapsIdAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUuidIdFilteringMapsIdAllPropertiesEquals(UuidIdFilteringMapsId expected, UuidIdFilteringMapsId actual) {
        assertUuidIdFilteringMapsIdAutoGeneratedPropertiesEquals(expected, actual);
        assertUuidIdFilteringMapsIdAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUuidIdFilteringMapsIdAllUpdatablePropertiesEquals(
        UuidIdFilteringMapsId expected,
        UuidIdFilteringMapsId actual
    ) {
        assertUuidIdFilteringMapsIdUpdatableFieldsEquals(expected, actual);
        assertUuidIdFilteringMapsIdUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the derived primary key is set correctly.
     *
     * @param entityToPersist the entity used to persist
     * @param persisted the persisted entity
     */
    public static void assertUuidIdFilteringMapsIdMapsIdRelationshipPersistedValue(
        UuidIdFilteringMapsId entityToPersist,
        UuidIdFilteringMapsId persisted
    ) {
        // Validate the id for MapsId, the ids must be same
        assertThat(entityToPersist.getUuidIdFiltering().getCustomId()).isEqualTo(persisted.getCustomId());
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUuidIdFilteringMapsIdAutoGeneratedPropertiesEquals(
        UuidIdFilteringMapsId expected,
        UuidIdFilteringMapsId actual
    ) {
        assertThat(actual)
            .as("Verify UuidIdFilteringMapsId auto generated properties")
            .satisfies(a -> assertThat(a.getCustomId()).as("check customId").isEqualTo(expected.getCustomId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUuidIdFilteringMapsIdUpdatableFieldsEquals(UuidIdFilteringMapsId expected, UuidIdFilteringMapsId actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUuidIdFilteringMapsIdUpdatableRelationshipsEquals(
        UuidIdFilteringMapsId expected,
        UuidIdFilteringMapsId actual
    ) {
        assertThat(actual)
            .as("Verify UuidIdFilteringMapsId relationships")
            .satisfies(a ->
                assertThat(a.getManyToManyMapsIdBacks()).as("check manyToManyMapsIdBacks").isEqualTo(expected.getManyToManyMapsIdBacks())
            );
    }
}
